on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Continuous Integration

jobs:
  installDependencies:
    name: NodeJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.3
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Upload Algolia Indices
        if: github['ref'] == 'refs/heads/master'
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        run: npm run upload
      - name: Publish via semantic-release
        if: github['ref'] == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
