on: push

name: CI / GitHub Actions

jobs:
  installDependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Job whats should only runs on master
      if: github['ref'] == 'refs/heads/master'
      run: echo unicorns
    # - name: Upload Algolia Indices
    #   env:
    #     ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    #     ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
    #   run: npm run upload
    # - name: Publish via semantic-release
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #   run: run semantic-release
